package:
  name: gkeyll
  version: "2.0"

source:
  path: ../../

build:
  number: 20200916

requirements:
  build:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.1.2
    - eigen3
  run:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.1.2
    - eigen3
    - postgkyl

about:
  home: https://github.com/ammarhakim/gkyl
  license: BSD
  license_file: LICENSE